name: itNe
description: A Flutter app with split screen camera and preview
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  permission_handler: ^11.0.1
  image: ^4.0.0
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0
  http: ^1.2.1
  google_mlkit_text_recognition: ^0.12.0
  provider: ^6.1.5+1
  shared_preferences: ^2.0.0
  google_mobile_ads: ^5.2.0
  in_app_purchase: ^3.1.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_strings.json
    - assets/app_config.json
    - assets/credit_config.json
